### 동아리 정보 업로드 테스트
POST http://{{url}}:{{port}}/clubs
Content-Type: application/json

{
  "name": "네터스",
  "hashtag": ["즐거운", "활기찬"],
  "current_number_of_people": 0,
  "maximum_number_of_people": 100,
  "deadline": "2022-02-02 00:00:00",
  "dues": 20000
}

### 동아리 썸네일 업로드 테스트
POST http://{{url}}:{{port}}/clubs/{{club_id}}/upload_thumbnail
Content-Type: multipart/form-data; boundary=thumbnail

--thumbnail
Content-Disposition: form-data; name="thumbnail"; filename="google_logo.png"

< ../resource/logos/google_logo.png

### 동아리 활동사진 업로드 테스트
POST http://{{url}}:{{port}}/clubs/{{club_id}}/upload_photos
Content-Type: multipart/form-data; boundary=photos

--photos
Content-Disposition: form-data; name="photos"; filename="act1.jpg"

< ../resource/pictures/act1.jpg

--photos
Content-Disposition: form-data; name="photos"; filename="act2.jpg"

< ../resource/pictures/act2.jpg

--photos
Content-Disposition: form-data; name="photos"; filename="act3.jpg"

< ../resource/pictures/act3.jpg