### 동아리 정보 업로드 테스트
POST http://{{url}}:{{port}}/clubs
Content-Type: application/json

{
  "name": "Neters",
  "hashtag": ["코딩", "친목", "학술동아리"],
  "current_number_of_people": 14,
  "maximum_number_of_people": 50,
  "deadline": "2022-05-21 00:00:00",
  "dues": 15000,
  "if_interview": true,
  "gender_ratio": "6:4",
  "main_activities": ["객체지향프로그래밍 교육", "백준 스터디 운영", "NPC개최", "친목활동", "게임대회"],
  "qualification": null
}

### 동아리 썸네일 업로드 테스트
POST http://{{url}}:{{port}}/clubs/{{club_id}}/upload_thumbnail
Content-Type: multipart/form-data; boundary=thumbnail

--thumbnail
Content-Disposition: form-data; name="thumbnail"; filename="google_logo.png"

< ../resource/logos/google_logo.png

### 동아리 활동사진 업로드 테스트
POST http://{{url}}:{{port}}/clubs/{{club_id}}/upload_photos
Content-Type: multipart/form-data; boundary=photos

--photos
Content-Disposition: form-data; name="photos"; filename="act1.jpg"

< ../resource/pictures/act1.jpg

--photos
Content-Disposition: form-data; name="photos"; filename="act2.jpg"

< ../resource/pictures/act2.jpg

--photos
Content-Disposition: form-data; name="photos"; filename="act3.jpg"

< ../resource/pictures/act3.jpg